/**
 * `loadSanmaimeSpecs()`: reads `.sanmaime` files at run time and registers their screens for
 * `$nimaime.verify()` (Node only). Used when Sanmaime is checked from hand-written code — e.g.
 * playwright-bdd step definitions — instead of from specs generated by `nimaime-gen`.
 */
import fs from 'node:fs';
import path from 'node:path';
import { formatDiagnostic, parse } from '../parser';
import { NimaimeRuntimeError } from './errors';
import { registerScreenSpec, screenSpecsFromDocument, type ScreenSpec } from './spec-registry';

/** Options of `loadSanmaimeSpecs`. */
export interface LoadSanmaimeSpecsOptions {
  /**
   * Default keyword language for files without a `# language:` directive (like the `language`
   * option of `defineSanmaimeConfig`). Default: `'en'`.
   */
  language?: string;
  /**
   * Directory that relative paths and globs are resolved against. Default: `process.cwd()` (the
   * directory Playwright was started from). Pass `import.meta.dirname` / `__dirname` to make the
   * patterns relative to the calling file.
   */
  cwd?: string;
}

/**
 * Reads, parses and registers every screen of the `.sanmaime` files matched by `files` (paths or
 * glob patterns such as `'specs/**\/*.sanmaime'`; a pattern starting with `!` excludes files;
 * `node_modules` is never searched). Returns the registered screen specs.
 *
 * Throws a `NimaimeRuntimeError` if no file matches, or listing every error diagnostic if a file
 * is not valid Sanmaime (nothing is registered then). Calling it again with the same files is
 * harmless: the screens are registered again from the same files.
 */
export async function loadSanmaimeSpecs(
  files: string | readonly string[],
  options: LoadSanmaimeSpecsOptions = {},
): Promise<ScreenSpec[]> {
  const cwd = path.resolve(options.cwd ?? process.cwd());
  const patterns = typeof files === 'string' ? [files] : files;
  const matched = await expandPatterns(patterns, cwd);
  if (matched.length === 0) {
    throw new NimaimeRuntimeError(
      `No .sanmaime file matches ${patterns.map((p) => `"${p}"`).join(', ')} (in ${cwd}).`,
    );
  }

  const screens: ScreenSpec[] = [];
  const errors: string[] = [];
  for (const file of matched) {
    const source = await fs.promises.readFile(file, 'utf8');
    const uri = displayPath(file);
    const { document, diagnostics } = parse(
      source,
      options.language === undefined ? { uri } : { uri, language: options.language },
    );
    const fileErrors = diagnostics.filter((d) => d.severity === 'error');
    if (fileErrors.length > 0) {
      errors.push(...fileErrors.map((d) => formatDiagnostic(d, uri)));
      continue;
    }
    screens.push(...screenSpecsFromDocument(document, file));
  }
  if (errors.length > 0) {
    throw new NimaimeRuntimeError(`Invalid Sanmaime specs:\n${errors.join('\n')}`);
  }
  for (const screen of screens) registerScreenSpec(screen);
  return screens;
}

/** `file` relative to the working directory when it is inside it (for messages). */
function displayPath(file: string): string {
  const rel = path.relative(process.cwd(), file);
  return rel === '' || rel.startsWith('..') || path.isAbsolute(rel)
    ? file
    : rel.split(path.sep).join('/');
}

/** Sorted, de-duplicated absolute paths of the files matched by `patterns` (see above). */
async function expandPatterns(patterns: readonly string[], cwd: string): Promise<string[]> {
  const glob = fs.promises.glob as typeof fs.promises.glob | undefined;
  if (typeof glob !== 'function') {
    throw new Error(
      `nimaime-han needs Node.js 22 or later to expand glob patterns (running ${process.version}).`,
    );
  }
  const include: string[] = [];
  const exclude: string[] = [];
  for (const raw of patterns) {
    const pattern = normalizePattern(raw);
    if (pattern.startsWith('!')) {
      const negated = normalizePattern(pattern.slice(1));
      if (negated !== '') exclude.push(negated);
    } else if (pattern !== '') {
      include.push(pattern);
    }
  }
  if (include.length === 0) return [];

  const found = new Set<string>();
  for await (const entry of glob(include, {
    cwd,
    exclude: (name: string) => path.basename(name) === 'node_modules',
  })) {
    const file = path.resolve(cwd, entry);
    if (path.relative(cwd, file).split(path.sep).includes('node_modules')) continue;
    if (exclude.some((negation) => matches(file, negation, cwd))) continue;
    if (!isFile(file)) continue;
    found.add(file);
  }
  return [...found].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
}

/** Strips a leading `./` and uses `/` separators, as glob patterns require. */
function normalizePattern(pattern: string): string {
  let result = pattern.trim().split(path.sep).join('/');
  while (result.startsWith('./')) result = result.slice(2);
  return result;
}

function matches(file: string, pattern: string, cwd: string): boolean {
  const subject = path.isAbsolute(pattern) ? file : path.relative(cwd, file);
  return path.matchesGlob(subject.split(path.sep).join('/'), pattern);
}

function isFile(file: string): boolean {
  try {
    return fs.statSync(file).isFile();
  } catch {
    return false;
  }
}
